#Messages
  missing_permission: "&cYou are not permitted to use this feature"
  feature_disabled: "&cThis feature is not available for this item"
#Permission
  customize_edit:
    set_itemFlags: true
    set_displayName: true
    set_enchants: true
    set_unbreakable: true
    set_attributeModifier: true
    set_color: true
    set_effects: true
