name: Itemcustomizer
version: '0.6.2'
main: me.vxrp.itemcustomizer.Itemcustomizer
api-version: '1.19'
commands:
  itemcustomizer:
    aliases: "customizer"
    permission: "customize.use"
  edit:
    aliases: "edititem"
    permission: "customize.edit"
  forceedit:
    aliases: "forceedititem"
    permission: "customize.admin"